import type { Metadata } from "next";
import { Noto_Serif_JP } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.scss";

const notoSerifJp = Noto_Serif_JP({
  weight: ["400", "500", "700"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <body className={notoSerifJp.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
