import type { Metadata } from "next";
import { Klee_One } from "next/font/google";

import Layout from "@/components/Layout";
import "./globals.scss";

const notoSerifJp = Klee_One({
  subsets: ["latin"],
  display: "swap",
  weight: "600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <body className={notoSerifJp.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
